import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma";
import { PrismaNeon } from "@prisma/adapter-neon";

const adapter = new PrismaNeon({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const words = [
  // EASY
  { word: "language", hint: "how people communicate with words", difficulty: "easy" },
  { word: "elephant", hint: "the largest land animal", difficulty: "easy" },
  { word: "umbrella", hint: "used to stay dry in the rain", difficulty: "easy" },
  { word: "calendar", hint: "tracks days weeks and months", difficulty: "easy" },
  { word: "beautiful", hint: "very pleasing to look at", difficulty: "easy" },
  { word: "mountain", hint: "a very large natural elevation of earth", difficulty: "easy" },
  { word: "sandwich", hint: "fillings between two slices of bread", difficulty: "easy" },
  { word: "chocolate", hint: "a sweet food made from cacao", difficulty: "easy" },
  { word: "adventure", hint: "an exciting and unusual experience", difficulty: "easy" },
  { word: "birthday", hint: "annual celebration of being born", difficulty: "easy" },
  { word: "together", hint: "in one place at the same time", difficulty: "easy" },
  { word: "tomorrow", hint: "the day after today", difficulty: "easy" },
  { word: "hospital", hint: "where sick people go for treatment", difficulty: "easy" },
  { word: "daughter", hint: "a female child", difficulty: "easy" },
  { word: "breakfast", hint: "the first meal of the day", difficulty: "easy" },
  // MEDIUM
  { word: "wednesday", hint: "the middle day of the working week", difficulty: "medium" },
  { word: "necessary", hint: "something you cannot do without", difficulty: "medium" },
  { word: "february", hint: "the shortest month of the year", difficulty: "medium" },
  { word: "separate", hint: "to keep or set apart", difficulty: "medium" },
  { word: "definitely", hint: "without any doubt at all", difficulty: "medium" },
  { word: "fluorescent", hint: "a type of bright glowing light", difficulty: "medium" },
  { word: "handkerchief", hint: "a cloth square for the nose", difficulty: "medium" },
  { word: "hypocrite", hint: "says one thing but does another", difficulty: "medium" },
  { word: "maintenance", hint: "keeping something in good condition", difficulty: "medium" },
  { word: "emergency", hint: "a sudden serious situation requiring action", difficulty: "medium" },
  { word: "perseverance", hint: "continuing despite difficulty", difficulty: "medium" },
  { word: "accommodate", hint: "to provide space or lodging for", difficulty: "medium" },
  { word: "embarrass", hint: "to cause someone to feel ashamed", difficulty: "medium" },
  { word: "government", hint: "system that rules a country", difficulty: "medium" },
  { word: "privilege", hint: "a special right or advantage", difficulty: "medium" },
  { word: "recommend", hint: "to suggest something favorably", difficulty: "medium" },
  { word: "environment", hint: "the natural world around us", difficulty: "medium" },
  { word: "immediately", hint: "right away without delay", difficulty: "medium" },
  { word: "particularly", hint: "to a greater degree than usual", difficulty: "medium" },
  { word: "temperature", hint: "how hot or cold something is", difficulty: "medium" },
  // HARD - 500+ words
  { word: "rhythm", hint: "music has a steady one", difficulty: "hard" },
  { word: "colonel", hint: "a military rank", difficulty: "hard" },
  { word: "pneumonia", hint: "a serious lung illness", difficulty: "hard" },
  { word: "occurrence", hint: "an event or incident", difficulty: "hard" },
  { word: "millennium", hint: "a span of one thousand years", difficulty: "hard" },
  { word: "questionnaire", hint: "a written list of questions", difficulty: "hard" },
  { word: "accommodation", hint: "a place to sleep and stay", difficulty: "hard" },
  { word: "bureaucracy", hint: "excessive rules and red tape", difficulty: "hard" },
  { word: "conscientious", hint: "careful and thorough in all you do", difficulty: "hard" },
  { word: "entrepreneur", hint: "someone who starts their own business", difficulty: "hard" },
  { word: "liaison", hint: "a communication link between groups", difficulty: "hard" },
  { word: "acquaintance", hint: "someone you know slightly", difficulty: "hard" },
  { word: "miscellaneous", hint: "a varied mixture of things", difficulty: "hard" },
  { word: "surreptitious", hint: "done secretly to avoid detection", difficulty: "hard" },
  { word: "acquiesce", hint: "to accept reluctantly without protest", difficulty: "hard" },
  { word: "ambiguous", hint: "open to more than one interpretation", difficulty: "hard" },
  { word: "anachronism", hint: "something out of its correct time period", difficulty: "hard" },
  { word: "anomalous", hint: "deviating from what is standard", difficulty: "hard" },
  { word: "anecdote", hint: "a short amusing personal story", difficulty: "hard" },
  { word: "antithesis", hint: "the direct opposite of something", difficulty: "hard" },
  { word: "belligerent", hint: "hostile and aggressive", difficulty: "hard" },
  { word: "beneficiary", hint: "a person who receives a benefit", difficulty: "hard" },
  { word: "bioluminescence", hint: "light produced by living organisms", difficulty: "hard" },
  { word: "caricature", hint: "an exaggerated portrayal for comic effect", difficulty: "hard" },
  { word: "catastrophic", hint: "involving sudden great disaster", difficulty: "hard" },
  { word: "chrysanthemum", hint: "a flowering plant with many petals", difficulty: "hard" },
  { word: "circumference", hint: "the outer boundary of a circle", difficulty: "hard" },
  { word: "clairvoyant", hint: "claiming to see the future", difficulty: "hard" },
  { word: "claustrophobia", hint: "fear of enclosed spaces", difficulty: "hard" },
  { word: "colloquial", hint: "informal everyday language", difficulty: "hard" },
  { word: "connoisseur", hint: "an expert judge in matters of taste", difficulty: "hard" },
  { word: "consanguinity", hint: "being descended from the same ancestor", difficulty: "hard" },
  { word: "contemptuous", hint: "showing utter disdain", difficulty: "hard" },
  { word: "contradiction", hint: "a combination of statements that cannot both be true", difficulty: "hard" },
  { word: "controversial", hint: "giving rise to public disagreement", difficulty: "hard" },
  { word: "convalescence", hint: "recovery from illness", difficulty: "hard" },
  { word: "copacetic", hint: "in excellent order", difficulty: "hard" },
  { word: "counterfeit", hint: "a fraudulent imitation", difficulty: "hard" },
  { word: "cryptography", hint: "the art of writing or solving codes", difficulty: "hard" },
  { word: "deleterious", hint: "causing harm or damage", difficulty: "hard" },
  { word: "demagogue", hint: "a leader who exploits popular emotions", difficulty: "hard" },
  { word: "denouement", hint: "the final resolution of a plot", difficulty: "hard" },
  { word: "dilapidated", hint: "in a state of disrepair from neglect", difficulty: "hard" },
  { word: "discombobulate", hint: "to disconcert or confuse someone", difficulty: "hard" },
  { word: "dissonance", hint: "a lack of harmony or agreement", difficulty: "hard" },
  { word: "doppelganger", hint: "a look-alike of another person", difficulty: "hard" },
  { word: "ebullient", hint: "cheerful and full of energy", difficulty: "hard" },
  { word: "eclectic", hint: "deriving from a broad range of sources", difficulty: "hard" },
  { word: "effervescent", hint: "vivacious and enthusiastic", difficulty: "hard" },
  { word: "egregious", hint: "outstandingly bad", difficulty: "hard" },
  { word: "elucidation", hint: "making something clear by explanation", difficulty: "hard" },
  { word: "embellishment", hint: "a decorative detail or feature added to something", difficulty: "hard" },
  { word: "ephemeral", hint: "lasting for a very short time", difficulty: "hard" },
  { word: "equanimity", hint: "mental calmness in difficult situations", difficulty: "hard" },
  { word: "equivocate", hint: "to use ambiguous language to conceal truth", difficulty: "hard" },
  { word: "evanescent", hint: "quickly fading from sight or memory", difficulty: "hard" },
  { word: "exacerbate", hint: "to make a problem worse", difficulty: "hard" },
  { word: "exhilarating", hint: "making one feel very happy and excited", difficulty: "hard" },
  { word: "exonerate", hint: "to officially absolve from blame", difficulty: "hard" },
  { word: "exorbitant", hint: "unreasonably high in price", difficulty: "hard" },
  { word: "expeditious", hint: "done with speed and efficiency", difficulty: "hard" },
  { word: "exquisite", hint: "extremely beautiful and delicate", difficulty: "hard" },
  { word: "extravagant", hint: "lacking restraint in spending", difficulty: "hard" },
  { word: "exuberant", hint: "filled with lively energy and excitement", difficulty: "hard" },
  { word: "facetious", hint: "treating serious issues with inappropriate humor", difficulty: "hard" },
  { word: "fallacious", hint: "based on a mistaken belief", difficulty: "hard" },
  { word: "fermentation", hint: "chemical breakdown by bacteria or yeast", difficulty: "hard" },
  { word: "flabbergasted", hint: "utterly astonished", difficulty: "hard" },
  { word: "flamboyant", hint: "tending to attract attention by confidence", difficulty: "hard" },
  { word: "fortuitous", hint: "happening by fortunate accident", difficulty: "hard" },
  { word: "frivolous", hint: "not having any serious purpose", difficulty: "hard" },
  { word: "garrulous", hint: "excessively talkative", difficulty: "hard" },
  { word: "grandiloquent", hint: "using fancy language to impress", difficulty: "hard" },
  { word: "gregarious", hint: "fond of company and sociable", difficulty: "hard" },
  { word: "guerrilla", hint: "a member of an irregular military group", difficulty: "hard" },
  { word: "halcyon", hint: "denoting a period of happiness and prosperity", difficulty: "hard" },
  { word: "harbinger", hint: "a person or thing that signals an event", difficulty: "hard" },
  { word: "hegemony", hint: "dominance of one group over others", difficulty: "hard" },
  { word: "heinous", hint: "utterly odious and wicked", difficulty: "hard" },
  { word: "hierarchical", hint: "organized in a ranking system", difficulty: "hard" },
  { word: "hyperbole", hint: "exaggerated statements not meant literally", difficulty: "hard" },
  { word: "idiosyncrasy", hint: "a distinctive peculiar habit or mannerism", difficulty: "hard" },
  { word: "ignominious", hint: "deserving or causing public disgrace", difficulty: "hard" },
  { word: "impeccable", hint: "in accordance with the highest standards", difficulty: "hard" },
  { word: "imperious", hint: "arrogant and domineering", difficulty: "hard" },
  { word: "impetuous", hint: "acting without thinking through consequences", difficulty: "hard" },
  { word: "incandescent", hint: "emitting light as a result of being heated", difficulty: "hard" },
  { word: "incongruent", hint: "not in harmony or keeping with surroundings", difficulty: "hard" },
  { word: "indigenous", hint: "originating in a particular place", difficulty: "hard" },
  { word: "indiscriminate", hint: "done without careful judgment", difficulty: "hard" },
  { word: "inexorable", hint: "impossible to stop or prevent", difficulty: "hard" },
  { word: "infallible", hint: "incapable of making mistakes", difficulty: "hard" },
  { word: "ingenious", hint: "clever and original", difficulty: "hard" },
  { word: "inquisitive", hint: "curious and eager to learn", difficulty: "hard" },
  { word: "inscrutable", hint: "impossible to understand or interpret", difficulty: "hard" },
  { word: "insidious", hint: "proceeding harmfully in a subtle way", difficulty: "hard" },
  { word: "insouciant", hint: "showing casual lack of concern", difficulty: "hard" },
  { word: "intransigent", hint: "refusing to change one's views", difficulty: "hard" },
  { word: "irascible", hint: "having a tendency to be easily angered", difficulty: "hard" },
  { word: "juggernaut", hint: "a huge powerful unstoppable force", difficulty: "hard" },
  { word: "juxtaposition", hint: "placing two things side by side for contrast", difficulty: "hard" },
  { word: "labyrinthine", hint: "complicated and difficult to navigate", difficulty: "hard" },
  { word: "lascivious", hint: "feeling or revealing sexual desire inappropriately", difficulty: "hard" },
  { word: "loquacious", hint: "tending to talk a great deal", difficulty: "hard" },
  { word: "lugubrious", hint: "looking or sounding mournful", difficulty: "hard" },
  { word: "magnanimous", hint: "generous or forgiving towards rivals", difficulty: "hard" },
  { word: "malapropism", hint: "mistaken use of a word in place of a similar one", difficulty: "hard" },
  { word: "malevolent", hint: "having or showing a wish to do evil", difficulty: "hard" },
  { word: "melancholic", hint: "having a feeling of pensive sadness", difficulty: "hard" },
  { word: "mendacious", hint: "not telling the truth", difficulty: "hard" },
  { word: "meticulous", hint: "showing great attention to detail", difficulty: "hard" },
  { word: "misanthrope", hint: "a person who dislikes humankind", difficulty: "hard" },
  { word: "mnemonic", hint: "a pattern that helps you remember something", difficulty: "hard" },
  { word: "multifarious", hint: "many and of various types", difficulty: "hard" },
  { word: "munificent", hint: "larger or more generous than is usual", difficulty: "hard" },
  { word: "nefarious", hint: "wicked and criminal in nature", difficulty: "hard" },
  { word: "nihilism", hint: "the rejection of all religious and moral principles", difficulty: "hard" },
  { word: "nonchalant", hint: "feeling casual and relaxed", difficulty: "hard" },
  { word: "obsequious", hint: "excessively compliant or servile", difficulty: "hard" },
  { word: "obstreperous", hint: "noisy and difficult to control", difficulty: "hard" },
  { word: "obtuse", hint: "annoyingly insensitive or slow to understand", difficulty: "hard" },
  { word: "ominous", hint: "giving the impression that something bad will happen", difficulty: "hard" },
  { word: "omniscient", hint: "knowing everything", difficulty: "hard" },
  { word: "oscillate", hint: "to move back and forth at a regular speed", difficulty: "hard" },
  { word: "ostentatious", hint: "characterized by vulgar or pretentious display", difficulty: "hard" },
  { word: "ostracize", hint: "to exclude from a society or group", difficulty: "hard" },
  { word: "overweening", hint: "showing too much confidence or pride", difficulty: "hard" },
  { word: "palimpsest", hint: "a manuscript where later writing overlies earlier", difficulty: "hard" },
  { word: "pandemonium", hint: "wild and noisy disorder or confusion", difficulty: "hard" },
  { word: "parsimonious", hint: "unwilling to spend money or use resources", difficulty: "hard" },
  { word: "pedantic", hint: "excessively concerned with minor details", difficulty: "hard" },
  { word: "perfidious", hint: "deceitful and untrustworthy", difficulty: "hard" },
  { word: "pejorative", hint: "expressing contempt or disapproval", difficulty: "hard" },
  { word: "penultimate", hint: "last but one in a series", difficulty: "hard" },
  { word: "perspicacious", hint: "having a ready insight into things", difficulty: "hard" },
  { word: "pertinacious", hint: "holding firmly to an opinion or course of action", difficulty: "hard" },
  { word: "philanthropy", hint: "desire to promote the welfare of others", difficulty: "hard" },
  { word: "phlegmatic", hint: "having an unemotional and calm disposition", difficulty: "hard" },
  { word: "placate", hint: "to make someone less angry or hostile", difficulty: "hard" },
  { word: "plausible", hint: "seeming reasonable or probable", difficulty: "hard" },
  { word: "poltergeist", hint: "a ghost that makes noises and moves objects", difficulty: "hard" },
  { word: "pomposity", hint: "the quality of being pompous", difficulty: "hard" },
  { word: "pragmatic", hint: "dealing with things sensibly and realistically", difficulty: "hard" },
  { word: "precarious", hint: "not securely held or in position", difficulty: "hard" },
  { word: "precipitous", hint: "dangerously high or steep", difficulty: "hard" },
  { word: "presumptuous", hint: "failing to observe the limits of what is permitted", difficulty: "hard" },
  { word: "precocious", hint: "having developed certain abilities at an earlier age", difficulty: "hard" },
  { word: "predilection", hint: "a preference or special liking for something", difficulty: "hard" },
  { word: "premonition", hint: "a strong feeling that something is about to happen", difficulty: "hard" },
  { word: "preposterous", hint: "contrary to reason or common sense", difficulty: "hard" },
  { word: "procrastinate", hint: "to delay or postpone action", difficulty: "hard" },
  { word: "prodigious", hint: "remarkably great in extent or size", difficulty: "hard" },
  { word: "profligate", hint: "recklessly extravagant or wasteful", difficulty: "hard" },
  { word: "proliferation", hint: "rapid increase in the number of something", difficulty: "hard" },
  { word: "propitious", hint: "giving or indicating a good chance of success", difficulty: "hard" },
  { word: "protagonist", hint: "the main character in a story", difficulty: "hard" },
  { word: "pugnacious", hint: "eager or quick to argue or fight", difficulty: "hard" },
  { word: "pusillanimous", hint: "lacking courage and resolution", difficulty: "hard" },
  { word: "querulous", hint: "complaining in a petulant way", difficulty: "hard" },
  { word: "quixotic", hint: "exceedingly idealistic and unrealistic", difficulty: "hard" },
  { word: "rambunctious", hint: "uncontrollably exuberant and boisterous", difficulty: "hard" },
  { word: "rancorous", hint: "characterized by bitterness or resentment", difficulty: "hard" },
  { word: "rapscallion", hint: "a mischievous person", difficulty: "hard" },
  { word: "recalcitrant", hint: "having an obstinately uncooperative attitude", difficulty: "hard" },
  { word: "recapitulate", hint: "summarize and state again the main points", difficulty: "hard" },
  { word: "reciprocate", hint: "to respond to a gesture or action in kind", difficulty: "hard" },
  { word: "reconciliation", hint: "restoration of friendly relations", difficulty: "hard" },
  { word: "recondite", hint: "not known by many people", difficulty: "hard" },
  { word: "relinquish", hint: "to voluntarily cease to keep or claim", difficulty: "hard" },
  { word: "reminiscence", hint: "a story told about a past event one remembers", difficulty: "hard" },
  { word: "reprehensible", hint: "deserving censure or condemnation", difficulty: "hard" },
  { word: "repudiate", hint: "to refuse to accept or be associated with", difficulty: "hard" },
  { word: "reticent", hint: "not revealing one's thoughts or feelings readily", difficulty: "hard" },
  { word: "rhetoric", hint: "the art of effective or persuasive speaking", difficulty: "hard" },
  { word: "rigmarole", hint: "a lengthy and complicated procedure", difficulty: "hard" },
  { word: "sanctimonious", hint: "making a show of being morally superior", difficulty: "hard" },
  { word: "sanguine", hint: "optimistic in a difficult situation", difficulty: "hard" },
  { word: "sardonic", hint: "grimly mocking or cynical", difficulty: "hard" },
  { word: "scintillating", hint: "sparkling or shining brightly", difficulty: "hard" },
  { word: "scrupulous", hint: "diligent and careful about doing things correctly", difficulty: "hard" },
  { word: "serendipity", hint: "the occurrence of events by happy accident", difficulty: "hard" },
  { word: "shibboleth", hint: "a custom that distinguishes one group from another", difficulty: "hard" },
  { word: "sinister", hint: "giving the impression that something harmful is likely", difficulty: "hard" },
  { word: "sobriquet", hint: "a nickname", difficulty: "hard" },
  { word: "soliloquy", hint: "an act of speaking one's thoughts aloud when alone", difficulty: "hard" },
  { word: "sophistry", hint: "use of clever but false arguments", difficulty: "hard" },
  { word: "soporific", hint: "tending to induce drowsiness or sleep", difficulty: "hard" },
  { word: "squalid", hint: "extremely dirty and unpleasant", difficulty: "hard" },
  { word: "stentorian", hint: "loud and powerful voice", difficulty: "hard" },
  { word: "stoicism", hint: "endurance of pain without complaint", difficulty: "hard" },
  { word: "subterranean", hint: "existing or occurring underground", difficulty: "hard" },
  { word: "sycophant", hint: "a person who flatters to gain favor", difficulty: "hard" },
  { word: "taciturn", hint: "reserved or uncommunicative in speech", difficulty: "hard" },
  { word: "tautology", hint: "saying the same thing twice in different words", difficulty: "hard" },
  { word: "tenacious", hint: "holding firmly to something", difficulty: "hard" },
  { word: "tergiversate", hint: "make conflicting or evasive statements", difficulty: "hard" },
  { word: "timorous", hint: "showing or suffering from nervousness", difficulty: "hard" },
  { word: "truculent", hint: "eager or quick to argue or fight", difficulty: "hard" },
  { word: "tumultuous", hint: "making a loud confused noise", difficulty: "hard" },
  { word: "ubiquitous", hint: "present everywhere or seeming to be everywhere", difficulty: "hard" },
  { word: "umbrage", hint: "offense or annoyance", difficulty: "hard" },
  { word: "unfathomable", hint: "incapable of being fully explored or understood", difficulty: "hard" },
  { word: "ungainly", hint: "moving in a clumsy and awkward manner", difficulty: "hard" },
  { word: "unscrupulous", hint: "having no moral principles", difficulty: "hard" },
  { word: "vacillate", hint: "to waver between different opinions", difficulty: "hard" },
  { word: "vainglorious", hint: "excessively proud of one's achievements", difficulty: "hard" },
  { word: "verisimilitude", hint: "the appearance of being true or real", difficulty: "hard" },
  { word: "vicarious", hint: "experienced in imagination through another person", difficulty: "hard" },
  { word: "vicissitude", hint: "a change of circumstances or fortune", difficulty: "hard" },
  { word: "vindictive", hint: "having or showing a desire to harm someone", difficulty: "hard" },
  { word: "visceral", hint: "relating to deep inward feelings", difficulty: "hard" },
  { word: "vitriolic", hint: "filled with bitter criticism or malice", difficulty: "hard" },
  { word: "vociferous", hint: "expressing views in a loud manner", difficulty: "hard" },
  { word: "voracious", hint: "wanting or devouring great quantities", difficulty: "hard" },
  { word: "waggish", hint: "humorous in a playful mischievous way", difficulty: "hard" },
  { word: "whimsical", hint: "playfully quaint or fanciful", difficulty: "hard" },
  { word: "wistful", hint: "having or showing a feeling of vague longing", difficulty: "hard" },
  { word: "zealous", hint: "having or showing zeal", difficulty: "hard" },
  { word: "zenith", hint: "the highest point reached by a celestial body", difficulty: "hard" },
  { word: "acrimony", hint: "bitterness or ill feeling", difficulty: "hard" },
  { word: "accolade", hint: "an award or privilege granted as a mark of honor", difficulty: "hard" },
  { word: "accoutrements", hint: "additional items of dress or equipment", difficulty: "hard" },
  { word: "acerbic", hint: "sharp and forthright in comment or tone", difficulty: "hard" },
  { word: "acolyte", hint: "a person assisting in a religious ceremony", difficulty: "hard" },
  { word: "admonish", hint: "to warn or reprimand someone firmly", difficulty: "hard" },
  { word: "aesthetics", hint: "a set of principles concerned with beauty", difficulty: "hard" },
  { word: "affidavit", hint: "a written statement confirmed by oath", difficulty: "hard" },
  { word: "affinity", hint: "a natural liking for or attraction to something", difficulty: "hard" },
  { word: "aggrandize", hint: "to increase the power or status of someone", difficulty: "hard" },
  { word: "agnostic", hint: "believes the existence of God is unknown", difficulty: "hard" },
  { word: "algorithm", hint: "a process or set of rules for solving a problem", difficulty: "hard" },
  { word: "alleviate", hint: "to make suffering less severe", difficulty: "hard" },
  { word: "alliteration", hint: "the occurrence of the same letter at the start of words", difficulty: "hard" },
  { word: "altruistic", hint: "showing a disinterested concern for others", difficulty: "hard" },
  { word: "amalgamate", hint: "to combine into a single unit", difficulty: "hard" },
  { word: "ameliorate", hint: "to make something bad better", difficulty: "hard" },
  { word: "amorphous", hint: "without a clearly defined shape", difficulty: "hard" },
  { word: "anaesthetic", hint: "a substance that induces insensitivity to pain", difficulty: "hard" },
  { word: "analogy", hint: "a comparison to explain something", difficulty: "hard" },
  { word: "ancillary", hint: "providing necessary support to the primary activities", difficulty: "hard" },
  { word: "annotate", hint: "to add notes to a text for explanation", difficulty: "hard" },
  { word: "annihilate", hint: "to destroy utterly", difficulty: "hard" },
  { word: "antagonistic", hint: "showing or feeling active opposition", difficulty: "hard" },
  { word: "anthropology", hint: "the study of human societies and cultures", difficulty: "hard" },
  { word: "antidote", hint: "a medicine taken to counteract poison", difficulty: "hard" },
  { word: "antiquated", hint: "old-fashioned or outdated", difficulty: "hard" },
  { word: "aphorism", hint: "a pithy observation expressing a general truth", difficulty: "hard" },
  { word: "apocryphal", hint: "of doubtful authenticity", difficulty: "hard" },
  { word: "apprehensive", hint: "anxious or fearful about the future", difficulty: "hard" },
  { word: "arbitrary", hint: "based on random choice rather than reason", difficulty: "hard" },
  { word: "archaic", hint: "very old or old-fashioned", difficulty: "hard" },
  { word: "arduous", hint: "involving or requiring strenuous effort", difficulty: "hard" },
  { word: "aristocratic", hint: "of or relating to the aristocracy", difficulty: "hard" },
  { word: "articulate", hint: "having or showing the ability to speak fluently", difficulty: "hard" },
  { word: "ascertain", hint: "to find something out for certain", difficulty: "hard" },
  { word: "asceticism", hint: "strict self-discipline for spiritual reasons", difficulty: "hard" },
  { word: "aspersion", hint: "an attack on the reputation of someone", difficulty: "hard" },
  { word: "assiduous", hint: "showing great care and perseverance", difficulty: "hard" },
  { word: "assuage", hint: "to make an unpleasant feeling less intense", difficulty: "hard" },
  { word: "astute", hint: "having an ability to accurately assess situations", difficulty: "hard" },
  { word: "atrocious", hint: "horrifyingly wicked", difficulty: "hard" },
  { word: "attenuate", hint: "to reduce the force or effect of something", difficulty: "hard" },
  { word: "audacious", hint: "showing a willingness to take bold risks", difficulty: "hard" },
  { word: "austerity", hint: "sternness or severity of manner or attitude", difficulty: "hard" },
  { word: "authenticity", hint: "the quality of being genuine", difficulty: "hard" },
  { word: "autonomous", hint: "having self-government", difficulty: "hard" },
  { word: "avarice", hint: "extreme greed for wealth", difficulty: "hard" },
  { word: "axiom", hint: "a statement taken to be true", difficulty: "hard" },
  { word: "ballyhoo", hint: "extravagant publicity or fuss", difficulty: "hard" },
  { word: "bamboozle", hint: "to trick or deceive someone", difficulty: "hard" },
  { word: "beguile", hint: "to charm or enchant someone", difficulty: "hard" },
  { word: "benediction", hint: "a prayer asking for divine blessing", difficulty: "hard" },
  { word: "benevolent", hint: "well-meaning and kindly", difficulty: "hard" },
  { word: "besmirch", hint: "to damage someone's reputation", difficulty: "hard" },
  { word: "bewilderment", hint: "a feeling of being puzzled or confused", difficulty: "hard" },
  { word: "bibliography", hint: "a list of books or articles referred to", difficulty: "hard" },
  { word: "bigotry", hint: "intolerance toward those with different opinions", difficulty: "hard" },
  { word: "blasphemous", hint: "sacrilegious against God or sacred things", difficulty: "hard" },
  { word: "blandishment", hint: "a flattering or pleasing statement", difficulty: "hard" },
  { word: "bombastic", hint: "high-sounding language with little meaning", difficulty: "hard" },
  { word: "braggadocio", hint: "boastful or arrogant behavior", difficulty: "hard" },
  { word: "brevity", hint: "concise and exact use of words", difficulty: "hard" },
  { word: "cacophony", hint: "a harsh discordant mixture of sounds", difficulty: "hard" },
  { word: "calumny", hint: "making false statements to damage reputation", difficulty: "hard" },
  { word: "candor", hint: "the quality of being open and honest", difficulty: "hard" },
  { word: "cantankerous", hint: "bad-tempered and argumentative", difficulty: "hard" },
  { word: "capitulate", hint: "to give up resistance", difficulty: "hard" },
  { word: "caprice", hint: "a sudden and unaccountable change of mood", difficulty: "hard" },
  { word: "capricious", hint: "given to sudden changes of mood", difficulty: "hard" },
  { word: "castigation", hint: "severe criticism or punishment", difficulty: "hard" },
  { word: "caustic", hint: "sarcastic in a scathing and bitter way", difficulty: "hard" },
  { word: "cavalcade", hint: "a formal procession of vehicles or people", difficulty: "hard" },
  { word: "cerebral", hint: "of or relating to the brain or intellect", difficulty: "hard" },
  { word: "charlatan", hint: "a person who claims expertise they don't have", difficulty: "hard" },
  { word: "chastise", hint: "to rebuke or reprimand severely", difficulty: "hard" },
  { word: "chicanery", hint: "the use of deception to achieve objectives", difficulty: "hard" },
  { word: "chivalrous", hint: "courteous and gallant, especially towards women", difficulty: "hard" },
  { word: "circumlocution", hint: "the use of many words to say something simply", difficulty: "hard" },
  { word: "circumspect", hint: "wary and unwilling to take risks", difficulty: "hard" },
  { word: "clamorous", hint: "making a loud and confused noise", difficulty: "hard" },
  { word: "clandestine", hint: "kept secret due to being illicit", difficulty: "hard" },
  { word: "clemency", hint: "mercy and leniency shown towards offenders", difficulty: "hard" },
  { word: "coalescing", hint: "coming together to form one mass", difficulty: "hard" },
  { word: "cognizant", hint: "having knowledge or being aware of", difficulty: "hard" },
  { word: "condescending", hint: "having an air of patronizing superiority", difficulty: "hard" },
  { word: "confluence", hint: "the junction of two rivers", difficulty: "hard" },
  { word: "confounded", hint: "cause to become confused or perplexed", difficulty: "hard" },
  { word: "congenial", hint: "pleasant because of similarities in personality", difficulty: "hard" },
  { word: "congruent", hint: "in agreement or harmony", difficulty: "hard" },
  { word: "conjecture", hint: "an opinion formed without proof", difficulty: "hard" },
  { word: "consecrate", hint: "to make or declare something sacred", difficulty: "hard" },
  { word: "consternation", hint: "a feeling of anxiety or dismay", difficulty: "hard" },
  { word: "contemplate", hint: "to look thoughtfully for a long time", difficulty: "hard" },
  { word: "contentious", hint: "causing or likely to cause controversy", difficulty: "hard" },
  { word: "contingency", hint: "a future event that is possible but not certain", difficulty: "hard" },
  { word: "contrite", hint: "feeling or expressing remorse", difficulty: "hard" },
  { word: "convoluted", hint: "extremely complex and difficult to follow", difficulty: "hard" },
  { word: "copious", hint: "abundant in supply or quantity", difficulty: "hard" },
  { word: "corroborate", hint: "to confirm or give support to a statement", difficulty: "hard" },
  { word: "countenance", hint: "a person's face or facial expression", difficulty: "hard" },
  { word: "covenant", hint: "a formal agreement between parties", difficulty: "hard" },
  { word: "covert", hint: "not openly acknowledged or displayed", difficulty: "hard" },
  { word: "culpable", hint: "deserving blame for a fault", difficulty: "hard" },
  { word: "cumbersome", hint: "large or heavy and difficult to handle", difficulty: "hard" },
  { word: "cupidity", hint: "greed for money or possessions", difficulty: "hard" },
  { word: "dauntless", hint: "showing fearlessness and determination", difficulty: "hard" },
  { word: "dearth", hint: "a scarcity or lack of something", difficulty: "hard" },
  { word: "debilitate", hint: "to make someone very weak and infirm", difficulty: "hard" },
  { word: "decorum", hint: "behavior in keeping with good taste", difficulty: "hard" },
  { word: "deferential", hint: "showing respect and high regard", difficulty: "hard" },
  { word: "defunct", hint: "no longer existing or functioning", difficulty: "hard" },
  { word: "delineate", hint: "to describe or indicate something precisely", difficulty: "hard" },
  { word: "delusion", hint: "an idiosyncratic belief held with conviction", difficulty: "hard" },
  { word: "demagogy", hint: "political activity seeking support by appeals to prejudice", difficulty: "hard" },
  { word: "demure", hint: "reserved and modest in manner or behavior", difficulty: "hard" },
  { word: "depredation", hint: "acts causing destruction or damage", difficulty: "hard" },
  { word: "derisive", hint: "expressing contempt or ridicule", difficulty: "hard" },
  { word: "desolation", hint: "a state of emptiness or devastation", difficulty: "hard" },
  { word: "despondent", hint: "in low spirits from loss of hope", difficulty: "hard" },
  { word: "destitute", hint: "without the basic necessities of life", difficulty: "hard" },
  { word: "dexterous", hint: "showing or having skill with the hands", difficulty: "hard" },
  { word: "diaphanous", hint: "light, delicate, and translucent", difficulty: "hard" },
  { word: "diatribe", hint: "a forceful and bitter verbal attack", difficulty: "hard" },
  { word: "diffident", hint: "modest or shy due to lack of self-confidence", difficulty: "hard" },
  { word: "digression", hint: "a temporary departure from the main subject", difficulty: "hard" },
  { word: "dilatory", hint: "slow to act", difficulty: "hard" },
  { word: "diligence", hint: "careful and persistent work or effort", difficulty: "hard" },
  { word: "diminutive", hint: "extremely or unusually small", difficulty: "hard" },
  { word: "disconsolate", hint: "very unhappy and unable to be comforted", difficulty: "hard" },
  { word: "discordant", hint: "disagreeing or incongruous", difficulty: "hard" },
  { word: "discretion", hint: "the quality of behaving without causing offense", difficulty: "hard" },
  { word: "disdain", hint: "the feeling that something is unworthy of consideration", difficulty: "hard" },
  { word: "disenchantment", hint: "a feeling of disappointment about ideals", difficulty: "hard" },
  { word: "disheveled", hint: "untidy in appearance", difficulty: "hard" },
  { word: "dismissive", hint: "treating something as unworthy of consideration", difficulty: "hard" },
  { word: "disparage", hint: "to regard or represent as being of little worth", difficulty: "hard" },
  { word: "disparate", hint: "fundamentally different or distinct", difficulty: "hard" },
  { word: "dispassionate", hint: "not influenced by strong emotion", difficulty: "hard" },
  { word: "dissolution", hint: "the closing down of an organization", difficulty: "hard" },
  { word: "doleful", hint: "expressing sorrow or mournful", difficulty: "hard" },
  { word: "dubious", hint: "hesitating or doubting", difficulty: "hard" },
  { word: "duplicity", hint: "deceitfulness in speech or conduct", difficulty: "hard" },
  { word: "eccentric", hint: "unconventional and slightly strange", difficulty: "hard" },
  { word: "edification", hint: "instruction intended to improve morally", difficulty: "hard" },
  { word: "effrontery", hint: "insolent or impertinent behavior", difficulty: "hard" },
  { word: "egalitarian", hint: "believing in equal rights for all people", difficulty: "hard" },
  { word: "egotistical", hint: "excessively conceited or absorbed in oneself", difficulty: "hard" },
  { word: "eloquent", hint: "fluent and persuasive in speaking", difficulty: "hard" },
  { word: "elusive", hint: "difficult to find or catch", difficulty: "hard" },
  { word: "emaciated", hint: "abnormally thin from illness or hunger", difficulty: "hard" },
  { word: "embezzlement", hint: "theft of funds placed in one's trust", difficulty: "hard" },
  { word: "empathy", hint: "the ability to understand another's feelings", difficulty: "hard" },
  { word: "empirical", hint: "based on observation or experience", difficulty: "hard" },
  { word: "emulate", hint: "to match or surpass by imitation", difficulty: "hard" },
  { word: "encumbrance", hint: "a burden or impediment", difficulty: "hard" },
  { word: "enervate", hint: "to make someone feel drained of energy", difficulty: "hard" },
  { word: "enigmatic", hint: "difficult to interpret or understand", difficulty: "hard" },
  { word: "enmity", hint: "the state of being actively opposed", difficulty: "hard" },
  { word: "enormity", hint: "the great or extreme scale of something bad", difficulty: "hard" },
  { word: "enunciate", hint: "to say or pronounce something clearly", difficulty: "hard" },
  { word: "equitable", hint: "fair and impartial", difficulty: "hard" },
  { word: "erudite", hint: "having great knowledge or learning", difficulty: "hard" },
  { word: "esoteric", hint: "intended only for a small number of people", difficulty: "hard" },
  { word: "euphemism", hint: "a mild expression substituted for a blunt one", difficulty: "hard" },
  { word: "evanescence", hint: "the process of fading and disappearing", difficulty: "hard" },
  { word: "evasive", hint: "tending to avoid giving direct answers", difficulty: "hard" },
  { word: "exasperation", hint: "intense irritation or frustration", difficulty: "hard" },
  { word: "excoriate", hint: "to criticize harshly", difficulty: "hard" },
  { word: "excruciating", hint: "intensely painful", difficulty: "hard" },
  { word: "exemplary", hint: "serving as a desirable model", difficulty: "hard" },
  { word: "exhaustive", hint: "including or considering all elements", difficulty: "hard" },
  { word: "expatriate", hint: "a person who lives outside their native country", difficulty: "hard" },
  { word: "expunge", hint: "to obliterate or remove completely", difficulty: "hard" },
  { word: "extemporaneous", hint: "spoken or done without preparation", difficulty: "hard" },
  { word: "extenuating", hint: "making an offense seem less serious", difficulty: "hard" },
  { word: "extraneous", hint: "irrelevant or unrelated to the subject", difficulty: "hard" },
  { word: "farcical", hint: "resembling a farce or absurdly futile", difficulty: "hard" },
  { word: "fastidious", hint: "very attentive to accuracy and detail", difficulty: "hard" },
  { word: "feckless", hint: "lacking initiative or strength of character", difficulty: "hard" },
  { word: "ferocious", hint: "savagely fierce or violent", difficulty: "hard" },
  { word: "fetid", hint: "smelling extremely unpleasant", difficulty: "hard" },
  { word: "filibuster", hint: "a prolonged speech to delay legislation", difficulty: "hard" },
  { word: "flippant", hint: "not showing appropriate seriousness", difficulty: "hard" },
  { word: "fortuitous", hint: "happening by chance rather than design", difficulty: "hard" },
  { word: "fraudulent", hint: "obtained or done by deception", difficulty: "hard" },
  { word: "frenetic", hint: "fast and energetic in a rather wild way", difficulty: "hard" },
  { word: "fulminate", hint: "to express vehement protest", difficulty: "hard" },
  { word: "funereal", hint: "having a mournful quality", difficulty: "hard" },
  { word: "futile", hint: "incapable of producing any useful result", difficulty: "hard" },
  { word: "galvanize", hint: "to shock or excite into taking action", difficulty: "hard" },
  { word: "garish", hint: "obtrusively bright and showy", difficulty: "hard" },
  { word: "gargantuan", hint: "enormous in size", difficulty: "hard" },
  { word: "germane", hint: "relevant to a subject under consideration", difficulty: "hard" },
  { word: "ghastly", hint: "causing great horror or fear", difficulty: "hard" },
  { word: "glib", hint: "fluent but showing little thought", difficulty: "hard" },
  { word: "gluttony", hint: "habitual greed or excess in eating", difficulty: "hard" },
  { word: "grandeur", hint: "splendor and impressiveness", difficulty: "hard" },
  { word: "gratuitous", hint: "uncalled for or unjustified", difficulty: "hard" },
  { word: "grievous", hint: "very severe or serious", difficulty: "hard" },
  { word: "grotesque", hint: "comically or repulsively ugly or distorted", difficulty: "hard" },
  { word: "grudging", hint: "given or allowed only reluctantly", difficulty: "hard" },
  { word: "guile", hint: "sly or cunning intelligence", difficulty: "hard" },
  { word: "hackneyed", hint: "lacking in originality; overused", difficulty: "hard" },
  { word: "harangue", hint: "a lengthy and aggressive speech", difficulty: "hard" },
  { word: "hedonism", hint: "the pursuit of pleasure as a way of life", difficulty: "hard" },
  { word: "heretical", hint: "believing in or practicing heresy", difficulty: "hard" },
  { word: "heterodox", hint: "not conforming to established beliefs", difficulty: "hard" },
  { word: "histrionic", hint: "overly theatrical in character", difficulty: "hard" },
  { word: "hubris", hint: "excessive pride or self-confidence", difficulty: "hard" },
  { word: "humility", hint: "a modest view of one's own importance", difficulty: "hard" },
  { word: "iconoclast", hint: "a person who attacks cherished beliefs", difficulty: "hard" },
  { word: "idyllic", hint: "like an idyll or extremely peaceful", difficulty: "hard" },
  { word: "ignominious", hint: "deserving or causing public disgrace", difficulty: "hard" },
  { word: "immutable", hint: "unchanging over time", difficulty: "hard" },
  { word: "impartial", hint: "treating all rivals equally", difficulty: "hard" },
  { word: "impassioned", hint: "filled with or showing great emotion", difficulty: "hard" },
  { word: "implacable", hint: "unable to be appeased", difficulty: "hard" },
  { word: "impugn", hint: "to dispute the truth or honesty of", difficulty: "hard" },
  { word: "inalienable", hint: "unable to be taken away or given away", difficulty: "hard" },
  { word: "incisive", hint: "intelligently analytical and clear-thinking", difficulty: "hard" },
  { word: "incomprehensible", hint: "not able to be understood", difficulty: "hard" },
  { word: "incredulous", hint: "unwilling or unable to believe something", difficulty: "hard" },
  { word: "indolent", hint: "wanting to avoid activity or exertion", difficulty: "hard" },
  { word: "ineffable", hint: "too great to be expressed in words", difficulty: "hard" },
  { word: "inequitable", hint: "not fair or reasonable", difficulty: "hard" },
  { word: "inextricable", hint: "impossible to disentangle from", difficulty: "hard" },
  { word: "infamous", hint: "well known for some bad quality", difficulty: "hard" },
  { word: "infuriate", hint: "to make someone extremely angry", difficulty: "hard" },
  { word: "inimical", hint: "tending to obstruct or harm", difficulty: "hard" },
  { word: "iniquity", hint: "immoral or grossly unfair behavior", difficulty: "hard" },
  { word: "innocuous", hint: "not harmful or offensive", difficulty: "hard" },
  { word: "insatiable", hint: "impossible to satisfy", difficulty: "hard" },
  { word: "insolent", hint: "showing a rude and arrogant lack of respect", difficulty: "hard" },
  { word: "insouciance", hint: "casual lack of concern", difficulty: "hard" },
  { word: "intemperate", hint: "having or showing a lack of self-control", difficulty: "hard" },
  { word: "interminable", hint: "endless or apparently endless", difficulty: "hard" },
  { word: "inveterate", hint: "having a particular habit long-established", difficulty: "hard" },
  { word: "invincible", hint: "too powerful to be defeated", difficulty: "hard" },
  { word: "irreconcilable", hint: "incompatible or unable to be resolved", difficulty: "hard" },
  { word: "irreverent", hint: "showing a lack of respect for sacred things", difficulty: "hard" },
  { word: "itinerant", hint: "traveling from place to place", difficulty: "hard" },
  { word: "jeopardize", hint: "to put something at risk of loss or harm", difficulty: "hard" },
  { word: "jocular", hint: "fond of jokes or given to joking", difficulty: "hard" },
  { word: "languid", hint: "displaying or having disinclination for exertion", difficulty: "hard" },
  { word: "laudatory", hint: "expressing praise and commendation", difficulty: "hard" },
  { word: "lethargy", hint: "a lack of energy and enthusiasm", difficulty: "hard" },
  { word: "levity", hint: "treatment of a serious matter with humor", difficulty: "hard" },
  { word: "libertine", hint: "a person who freely indulges in pleasure", difficulty: "hard" },
  { word: "litigious", hint: "tending to resort to lawsuits", difficulty: "hard" },
  { word: "magniloquent", hint: "using high-flown or bombastic language", difficulty: "hard" },
  { word: "malfeasance", hint: "wrongdoing by a public official", difficulty: "hard" },
  { word: "malicious", hint: "characterized by malice; intending to do harm", difficulty: "hard" },
  { word: "malingerer", hint: "a person who fakes illness to escape duty", difficulty: "hard" },
  { word: "malleable", hint: "easily influenced or shaped", difficulty: "hard" },
  { word: "manipulative", hint: "exercising control over others cleverly", difficulty: "hard" },
  { word: "maudlin", hint: "self-pityingly or tearfully sentimental", difficulty: "hard" },
  { word: "maverick", hint: "an independent-minded person", difficulty: "hard" },
  { word: "mayhem", hint: "violent or extreme disorder and confusion", difficulty: "hard" },
  { word: "mellifluous", hint: "sweet or musical and pleasant to hear", difficulty: "hard" },
  { word: "mendicant", hint: "a person who lives by begging", difficulty: "hard" },
  { word: "mercurial", hint: "subject to sudden changes of mood", difficulty: "hard" },
  { word: "metamorphosis", hint: "a change of form by natural process", difficulty: "hard" },
  { word: "microcosm", hint: "a community regarded as encapsulating the world", difficulty: "hard" },
  { word: "mirth", hint: "amusement especially as expressed in laughter", difficulty: "hard" },
  { word: "mitigate", hint: "to make less severe or serious", difficulty: "hard" },
  { word: "modicum", hint: "a small quantity of a particular thing", difficulty: "hard" },
  { word: "mollify", hint: "to appease the anger or anxiety of someone", difficulty: "hard" },
  { word: "morose", hint: "sullen and ill-tempered", difficulty: "hard" },
  { word: "mundane", hint: "lacking interest or excitement; dull", difficulty: "hard" },
  { word: "narcissistic", hint: "having an excessive interest in oneself", difficulty: "hard" },
  { word: "nebulous", hint: "in the form of a cloud or haze", difficulty: "hard" },
  { word: "negate", hint: "to nullify or make ineffective", difficulty: "hard" },
  { word: "nepotism", hint: "favoring relatives in appointment to positions", difficulty: "hard" },
  { word: "neurotic", hint: "abnormally sensitive or obsessive behavior", difficulty: "hard" },
  { word: "nonchalance", hint: "a state of relaxed unconcern", difficulty: "hard" },
  { word: "nostalgia", hint: "a sentimental longing for the past", difficulty: "hard" },
  { word: "notorious", hint: "famous for some bad quality", difficulty: "hard" },
  { word: "nullify", hint: "to make legally null and void", difficulty: "hard" },
  { word: "obdurate", hint: "stubbornly refusing to change one's opinion", difficulty: "hard" },
  { word: "obesity", hint: "the condition of being grossly overweight", difficulty: "hard" },
  { word: "obliterate", hint: "to destroy utterly or wipe out", difficulty: "hard" },
  { word: "oblivious", hint: "not aware of what is happening around one", difficulty: "hard" },
  { word: "obsequiousness", hint: "excessive eagerness to serve or please", difficulty: "hard" },
  { word: "obsolescence", hint: "the process of becoming outdated", difficulty: "hard" },
  { word: "odious", hint: "extremely unpleasant or repulsive", difficulty: "hard" },
  { word: "oligarchy", hint: "rule by a small group of people", difficulty: "hard" },
  { word: "opprobrium", hint: "harsh criticism or censure", difficulty: "hard" },
  { word: "opulence", hint: "great wealth or luxuriousness", difficulty: "hard" },
  { word: "ordinate", hint: "to appoint to a ministerial role", difficulty: "hard" },
  { word: "ostentatiously", hint: "in a way designed to impress or attract notice", difficulty: "hard" },
  { word: "overwrought", hint: "in a state of excessive nervous agitation", difficulty: "hard" },
  { word: "painstaking", hint: "done with or employing careful attention", difficulty: "hard" },
  { word: "palpable", hint: "able to be touched or felt", difficulty: "hard" },
  { word: "panacea", hint: "a solution for all difficulties or diseases", difficulty: "hard" },
  { word: "panegyric", hint: "a public speech of praise", difficulty: "hard" },
  { word: "paradigm", hint: "a typical example or pattern of something", difficulty: "hard" },
  { word: "paradoxical", hint: "seemingly contradictory but nonetheless true", difficulty: "hard" },
  { word: "paranoia", hint: "unjustified suspicion and mistrust of others", difficulty: "hard" },
  { word: "paraphernalia", hint: "miscellaneous articles or equipment", difficulty: "hard" },
  { word: "pariah", hint: "an outcast person or animal", difficulty: "hard" },
  { word: "partisan", hint: "a strong supporter of a party or cause", difficulty: "hard" },
  { word: "paternalistic", hint: "limiting freedom for the person's own good", difficulty: "hard" },
  { word: "pathological", hint: "compulsive or obsessive behavior", difficulty: "hard" },
  { word: "patronize", hint: "to treat someone as if they are inferior", difficulty: "hard" },
  { word: "paucity", hint: "the presence of something in small quantities", difficulty: "hard" },
  { word: "penitent", hint: "feeling or showing regret for wrongdoing", difficulty: "hard" },
  { word: "perennial", hint: "lasting or existing for a long time", difficulty: "hard" },
  { word: "perilous", hint: "full of danger or risk", difficulty: "hard" },
  { word: "pernicious", hint: "having a harmful effect in a gradual way", difficulty: "hard" },
  { word: "perplexed", hint: "completely baffled or puzzled", difficulty: "hard" },
  { word: "persecute", hint: "to subject someone to hostility or ill-treatment", difficulty: "hard" },
  { word: "pertain", hint: "to be appropriate or related to something", difficulty: "hard" },
  { word: "perturbation", hint: "anxiety or mental uneasiness", difficulty: "hard" },
  { word: "philanthropist", hint: "a person who donates to good causes", difficulty: "hard" },
  { word: "pillory", hint: "to attack or ridicule publicly", difficulty: "hard" },
  { word: "pitiless", hint: "showing no pity or mercy", difficulty: "hard" },
  { word: "placid", hint: "not easily upset or excited", difficulty: "hard" },
  { word: "platitude", hint: "a remark so often used it is no longer interesting", difficulty: "hard" },
  { word: "plebeian", hint: "of or belonging to the common people", difficulty: "hard" },
  { word: "plethora", hint: "a large or excessive amount of something", difficulty: "hard" },
  { word: "polemical", hint: "of or involving strongly critical arguments", difficulty: "hard" },
  { word: "polyphonic", hint: "having many voices or sounds", difficulty: "hard" },
  { word: "pontificate", hint: "to express opinions in a pompous way", difficulty: "hard" },
  { word: "portentous", hint: "of or like a portent or warning", difficulty: "hard" },
  { word: "posterity", hint: "all future generations", difficulty: "hard" },
  { word: "posturing", hint: "behaving in a way intended to impress", difficulty: "hard" },
  { word: "pragmatism", hint: "dealing with things sensibly and realistically", difficulty: "hard" },
  { word: "preclude", hint: "to prevent from happening", difficulty: "hard" },
  { word: "preemptive", hint: "taken as a measure against something anticipated", difficulty: "hard" },
  { word: "preponderance", hint: "the quality of being greater in number", difficulty: "hard" },
  { word: "presuppose", hint: "to require as a prior condition", difficulty: "hard" },
  { word: "pretentious", hint: "attempting to impress by affecting merit", difficulty: "hard" },
  { word: "prevaricate", hint: "to speak or act in an evasive way", difficulty: "hard" },
  { word: "probity", hint: "the quality of having strong moral principles", difficulty: "hard" },
  { word: "proclivity", hint: "a tendency to do something regularly", difficulty: "hard" },
  { word: "profundity", hint: "deep insight or very great knowledge", difficulty: "hard" },
  { word: "prohibitive", hint: "serving to forbid or prevent something", difficulty: "hard" },
  { word: "promulgate", hint: "to make known by official proclamation", difficulty: "hard" },
  { word: "propagandist", hint: "a person who spreads propaganda", difficulty: "hard" },
  { word: "propitious", hint: "giving or indicating a good chance of success", difficulty: "hard" },
  { word: "propriety", hint: "conformity to conventionally accepted behavior", difficulty: "hard" },
  { word: "protracted", hint: "lasting for a long time", difficulty: "hard" },
  { word: "provocation", hint: "an action that causes anger or resentment", difficulty: "hard" },
  { word: "prudish", hint: "having or revealing a tendency to be shocked", difficulty: "hard" },
  { word: "punctilious", hint: "showing great attention to etiquette", difficulty: "hard" },
  { word: "quandary", hint: "a state of perplexity or uncertainty", difficulty: "hard" },
  { word: "rapacious", hint: "aggressively greedy or grasping", difficulty: "hard" },
  { word: "rarefied", hint: "belonging to a select group", difficulty: "hard" },
  { word: "raucous", hint: "making a harsh loud noise", difficulty: "hard" },
  { word: "reckoning", hint: "the action of calculating or estimating something", difficulty: "hard" },
  { word: "rectitude", hint: "morally correct behavior", difficulty: "hard" },
  { word: "redolent", hint: "strongly reminiscent or suggestive of something", difficulty: "hard" },
  { word: "refutation", hint: "the action of proving a statement to be wrong", difficulty: "hard" },
  { word: "relentless", hint: "unceasingly intense", difficulty: "hard" },
  { word: "renegade", hint: "a person who deserts a group", difficulty: "hard" },
  { word: "replete", hint: "filled or well-supplied with something", difficulty: "hard" },
  { word: "reprobate", hint: "an unprincipled person", difficulty: "hard" },
  { word: "resentment", hint: "bitter indignation at unfair treatment", difficulty: "hard" },
  { word: "resilient", hint: "able to withstand or recover quickly from difficulties", difficulty: "hard" },
  { word: "resolution", hint: "a firm decision to do something", difficulty: "hard" },
  { word: "resplendent", hint: "attractive and impressive through being richly colorful", difficulty: "hard" },
  { word: "reticence", hint: "the quality of being reserved in manner", difficulty: "hard" },
  { word: "retribution", hint: "punishment inflicted as vengeance", difficulty: "hard" },
  { word: "revulsion", hint: "a sense of disgust and loathing", difficulty: "hard" },
  { word: "rhetorical", hint: "relating to the art of effective speaking", difficulty: "hard" },
  { word: "righteousness", hint: "the quality of being morally correct", difficulty: "hard" },
  { word: "ruthless", hint: "having no pity for others", difficulty: "hard" },
  { word: "sagacious", hint: "having good judgment or keen perception", difficulty: "hard" },
  { word: "salient", hint: "most noticeable or important", difficulty: "hard" },
  { word: "salutary", hint: "producing good results or beneficial", difficulty: "hard" },
  { word: "satiate", hint: "to satisfy fully", difficulty: "hard" },
  { word: "scathing", hint: "severely critical", difficulty: "hard" },
  { word: "schadenfreude", hint: "pleasure from another's misfortune", difficulty: "hard" },
  { word: "schism", hint: "a split or division between groups", difficulty: "hard" },
  { word: "seismic", hint: "of enormous proportions or effect", difficulty: "hard" },
  { word: "sensationalism", hint: "presenting information to provoke public interest", difficulty: "hard" },
  { word: "sentimentality", hint: "exaggerated tenderness or nostalgia", difficulty: "hard" },
  { word: "servile", hint: "having an attitude of a slave", difficulty: "hard" },
  { word: "shameless", hint: "showing no shame or embarrassment", difficulty: "hard" },
  { word: "skulduggery", hint: "devious behavior", difficulty: "hard" },
  { word: "solemnity", hint: "the state of being serious and dignified", difficulty: "hard" },
  { word: "solicitous", hint: "showing interest or concern for someone", difficulty: "hard" },
  { word: "solipsism", hint: "the view that only one's own mind is certain", difficulty: "hard" },
  { word: "sophism", hint: "a false argument especially used to deceive", difficulty: "hard" },
  { word: "specious", hint: "apparently reasonable but actually wrong", difficulty: "hard" },
  { word: "spurious", hint: "not genuine or authentic", difficulty: "hard" },
  { word: "stagnation", hint: "the state of not flowing or moving", difficulty: "hard" },
  { word: "stamina", hint: "the ability to sustain prolonged effort", difficulty: "hard" },
  { word: "steadfast", hint: "resolutely firm and unwavering", difficulty: "hard" },
  { word: "stigmatize", hint: "to describe something as worthy of disgrace", difficulty: "hard" },
  { word: "stipulate", hint: "to demand or specify as part of an agreement", difficulty: "hard" },
  { word: "stolid", hint: "calm and dependable and showing little emotion", difficulty: "hard" },
  { word: "stratagem", hint: "a plan or scheme to outwit an opponent", difficulty: "hard" },
  { word: "subversive", hint: "seeking to undermine an established institution", difficulty: "hard" },
  { word: "succinct", hint: "briefly and clearly expressed", difficulty: "hard" },
  { word: "supercilious", hint: "behaving as if one is superior to others", difficulty: "hard" },
  { word: "superfluous", hint: "unnecessary especially through being more than enough", difficulty: "hard" },
  { word: "suppression", hint: "the action of putting an end to something", difficulty: "hard" },
  { word: "susceptible", hint: "likely or liable to be influenced by something", difficulty: "hard" },
  { word: "sycophancy", hint: "excessive flattery to gain favor", difficulty: "hard" },
  { word: "systematic", hint: "done according to a fixed plan", difficulty: "hard" },
  { word: "tangential", hint: "relating to a tangent; diverging from a course", difficulty: "hard" },
  { word: "tantalize", hint: "to torment with something desired but out of reach", difficulty: "hard" },
  { word: "temerity", hint: "excessive confidence or boldness", difficulty: "hard" },
  { word: "temperamental", hint: "liable to unreasonable changes of mood", difficulty: "hard" },
  { word: "tendentious", hint: "promoting a particular cause", difficulty: "hard" },
  { word: "terse", hint: "sparing in words", difficulty: "hard" },
  { word: "tirade", hint: "a long angry speech of criticism", difficulty: "hard" },
  { word: "toady", hint: "a person who flatters for personal gain", difficulty: "hard" },
  { word: "torpor", hint: "a state of physical or mental inactivity", difficulty: "hard" },
  { word: "tortuous", hint: "full of twists and turns", difficulty: "hard" },
  { word: "totalitarian", hint: "relating to a system of government that has no rival", difficulty: "hard" },
  { word: "transgression", hint: "an act that goes against a rule or principle", difficulty: "hard" },
  { word: "treacherous", hint: "guilty of betrayal", difficulty: "hard" },
  { word: "tremulous", hint: "shaking or quivering slightly", difficulty: "hard" },
  { word: "trifling", hint: "unimportant or not serious", difficulty: "hard" },
  { word: "turbulent", hint: "moving unsteadily with much agitation", difficulty: "hard" },
  { word: "turpitude", hint: "wickedness and depravity", difficulty: "hard" },
  { word: "tyrannical", hint: "exercising power in a cruel way", difficulty: "hard" },
  { word: "unctuous", hint: "excessively flattering in an insincere way", difficulty: "hard" },
  { word: "unprecedented", hint: "never done or known before", difficulty: "hard" },
  { word: "unwavering", hint: "steadfast or resolute", difficulty: "hard" },
  { word: "usurpation", hint: "taking authority illegally", difficulty: "hard" },
  { word: "vacuous", hint: "having or showing a lack of thought", difficulty: "hard" },
  { word: "venal", hint: "susceptible to bribery", difficulty: "hard" },
  { word: "veneration", hint: "great respect or reverence", difficulty: "hard" },
  { word: "vexatious", hint: "causing or tending to cause annoyance", difficulty: "hard" },
  { word: "vigilance", hint: "the action of keeping careful watch", difficulty: "hard" },
  { word: "vilification", hint: "abusively disparaging speech or writing", difficulty: "hard" },
  { word: "vindication", hint: "the action of showing something to be right", difficulty: "hard" },
  { word: "viscous", hint: "having a thick sticky consistency", difficulty: "hard" },
  { word: "vituperate", hint: "to blame or insult in strong terms", difficulty: "hard" },
  { word: "voluminous", hint: "occupying or containing much space", difficulty: "hard" },
  { word: "voluptuous", hint: "relating to luxury and sensual pleasure", difficulty: "hard" },
  { word: "voraciously", hint: "in a way that shows great enthusiasm", difficulty: "hard" },
  { word: "wanton", hint: "deliberate and unprovoked", difficulty: "hard" },
  { word: "wistfulness", hint: "a feeling of vague or regretful longing", difficulty: "hard" },
  { word: "xenophobia", hint: "dislike of or prejudice against foreigners", difficulty: "hard" },
  { word: "zealotry", hint: "the behavior or attitude of a zealot", difficulty: "hard" },
  { word: "zephyr", hint: "a soft gentle breeze", difficulty: "hard" },
];

async function main() {
  console.log("Seeding database...");
  let count = 0;
  for (const w of words) {
    await prisma.word.upsert({
      where: { word: w.word },
      update: {},
      create: w,
    });
    count++;
  }
  const hard = words.filter(w => w.difficulty === "hard").length;
  console.log(`Seeded ${count} words (${hard} hard)`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
